package models

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-08-04T18:44:43+08:00
** Author: CrazyThursdayV50
 */

type ExamInfo1 struct {
	Id                     int64   `gorm:"column:id;type:INT;primaryKey;not null;autoIncrement" json:"id"`
	DetailId               int64   `gorm:"column:detail_id;type:BIGINT;not null" json:"detail_id"`
	StrengthAnalysis       *string `gorm:"column:strength_analysis;type:TEXT" json:"strength_analysis"`
	ImprovementSuggestions *string `gorm:"column:improvement_suggestions;type:TEXT" json:"improvement_suggestions"`
}

func exam_info1_id() Column[int64] {
	return "id"
}

func (s *ExamInfo1) ColumnId() Column[int64] {
	return exam_info1_id()
}

func exam_info1_detail_id() Column[int64] {
	return "detail_id"
}

func (s *ExamInfo1) ColumnDetailId() Column[int64] {
	return exam_info1_detail_id()
}

func exam_info1_strength_analysis() Column[*string] {
	return "strength_analysis"
}

func (s *ExamInfo1) ColumnStrengthAnalysis() Column[*string] {
	return exam_info1_strength_analysis()
}

func exam_info1_improvement_suggestions() Column[*string] {
	return "improvement_suggestions"
}

func (s *ExamInfo1) ColumnImprovementSuggestions() Column[*string] {
	return exam_info1_improvement_suggestions()
}

func (t *ExamInfo1) TableName() string {
	return Schema() + ".exam_info1"
}
